//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SafeNetWS.ENettService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_VNettService", Namespace="http://www.enett.com/services/vnett/2010/09")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    public partial class vNettService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IssueVANOperationCompleted;
        
        private System.Threading.SendOrPostCallback AmendVANOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelVANOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVANDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFxQuoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public vNettService() {
            this.Url = global::SafeNetWS.Properties.Settings.Default.SafeNetWS_ENettService_vNettService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IssueVANCompletedEventHandler IssueVANCompleted;
        
        /// <remarks/>
        public event AmendVANCompletedEventHandler AmendVANCompleted;
        
        /// <remarks/>
        public event CancelVANCompletedEventHandler CancelVANCompleted;
        
        /// <remarks/>
        public event GetVANDetailsCompletedEventHandler GetVANDetailsCompleted;
        
        /// <remarks/>
        public event GetFxQuoteCompletedEventHandler GetFxQuoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("IssueVNettVANRequest", RequestNamespace="http://www.enett.com/services/vnett/2010/09", ResponseNamespace="http://www.enett.com/services/vnett/2010/09", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IssueVNettVANResponse IssueVAN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IssueVNettVANRequest issueVANRequest) {
            object[] results = this.Invoke("IssueVAN", new object[] {
                        issueVANRequest});
            return ((IssueVNettVANResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IssueVANAsync(IssueVNettVANRequest issueVANRequest) {
            this.IssueVANAsync(issueVANRequest, null);
        }
        
        /// <remarks/>
        public void IssueVANAsync(IssueVNettVANRequest issueVANRequest, object userState) {
            if ((this.IssueVANOperationCompleted == null)) {
                this.IssueVANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIssueVANOperationCompleted);
            }
            this.InvokeAsync("IssueVAN", new object[] {
                        issueVANRequest}, this.IssueVANOperationCompleted, userState);
        }
        
        private void OnIssueVANOperationCompleted(object arg) {
            if ((this.IssueVANCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IssueVANCompleted(this, new IssueVANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("AmendVNettVANRequest", RequestNamespace="http://www.enett.com/services/vnett/2010/09", ResponseNamespace="http://www.enett.com/services/vnett/2010/09", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AmendVNettVANResponse AmendVAN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AmendVNettVANRequest amendVANRequest) {
            object[] results = this.Invoke("AmendVAN", new object[] {
                        amendVANRequest});
            return ((AmendVNettVANResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AmendVANAsync(AmendVNettVANRequest amendVANRequest) {
            this.AmendVANAsync(amendVANRequest, null);
        }
        
        /// <remarks/>
        public void AmendVANAsync(AmendVNettVANRequest amendVANRequest, object userState) {
            if ((this.AmendVANOperationCompleted == null)) {
                this.AmendVANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAmendVANOperationCompleted);
            }
            this.InvokeAsync("AmendVAN", new object[] {
                        amendVANRequest}, this.AmendVANOperationCompleted, userState);
        }
        
        private void OnAmendVANOperationCompleted(object arg) {
            if ((this.AmendVANCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AmendVANCompleted(this, new AmendVANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("CancelVNettVANRequest", RequestNamespace="http://www.enett.com/services/vnett/2010/09", ResponseNamespace="http://www.enett.com/services/vnett/2010/09", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CancelVNettVANResponse CancelVAN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CancelVNettVANRequest cancelVANRequest) {
            object[] results = this.Invoke("CancelVAN", new object[] {
                        cancelVANRequest});
            return ((CancelVNettVANResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CancelVANAsync(CancelVNettVANRequest cancelVANRequest) {
            this.CancelVANAsync(cancelVANRequest, null);
        }
        
        /// <remarks/>
        public void CancelVANAsync(CancelVNettVANRequest cancelVANRequest, object userState) {
            if ((this.CancelVANOperationCompleted == null)) {
                this.CancelVANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelVANOperationCompleted);
            }
            this.InvokeAsync("CancelVAN", new object[] {
                        cancelVANRequest}, this.CancelVANOperationCompleted, userState);
        }
        
        private void OnCancelVANOperationCompleted(object arg) {
            if ((this.CancelVANCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelVANCompleted(this, new CancelVANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetVNettVANRequest", RequestNamespace="http://www.enett.com/services/vnett/2010/09", ResponseNamespace="http://www.enett.com/services/vnett/2010/09", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetVNettVANResponse GetVANDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetVNettVANRequest getVANRequest) {
            object[] results = this.Invoke("GetVANDetails", new object[] {
                        getVANRequest});
            return ((GetVNettVANResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetVANDetailsAsync(GetVNettVANRequest getVANRequest) {
            this.GetVANDetailsAsync(getVANRequest, null);
        }
        
        /// <remarks/>
        public void GetVANDetailsAsync(GetVNettVANRequest getVANRequest, object userState) {
            if ((this.GetVANDetailsOperationCompleted == null)) {
                this.GetVANDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVANDetailsOperationCompleted);
            }
            this.InvokeAsync("GetVANDetails", new object[] {
                        getVANRequest}, this.GetVANDetailsOperationCompleted, userState);
        }
        
        private void OnGetVANDetailsOperationCompleted(object arg) {
            if ((this.GetVANDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVANDetailsCompleted(this, new GetVANDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("GetVNettFxQuoteRequest", RequestNamespace="http://www.enett.com/services/vnett/2010/09", ResponseNamespace="http://www.enett.com/services/vnett/2010/09", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetVNettFxQuoteResponse GetFxQuote([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GetVNettFxQuoteRequest getVNettFxQuoteRequest) {
            object[] results = this.Invoke("GetFxQuote", new object[] {
                        getVNettFxQuoteRequest});
            return ((GetVNettFxQuoteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetFxQuoteAsync(GetVNettFxQuoteRequest getVNettFxQuoteRequest) {
            this.GetFxQuoteAsync(getVNettFxQuoteRequest, null);
        }
        
        /// <remarks/>
        public void GetFxQuoteAsync(GetVNettFxQuoteRequest getVNettFxQuoteRequest, object userState) {
            if ((this.GetFxQuoteOperationCompleted == null)) {
                this.GetFxQuoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFxQuoteOperationCompleted);
            }
            this.InvokeAsync("GetFxQuote", new object[] {
                        getVNettFxQuoteRequest}, this.GetFxQuoteOperationCompleted, userState);
        }
        
        private void OnGetFxQuoteOperationCompleted(object arg) {
            if ((this.GetFxQuoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFxQuoteCompleted(this, new GetFxQuoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2013/07")]
    public partial class IssueVNettVANRequest : BaseRequest {
        
        private string activationDateField;
        
        private string cardTypeNameField;
        
        private string countryCodeField;
        
        private string currencyCodeField;
        
        private string expiryDateField;
        
        private string integratorReferenceField;
        
        private bool isInstantAuthRequiredField;
        
        private bool isMultiUseField;
        
        private bool isMultiUseFieldSpecified;
        
        private int issuedToEcnField;
        
        private long maximumAuthorisationAmountField;
        
        private string merchantCategoryCodeField;
        
        private string merchantCategoryNameField;
        
        private long minimumAuthorisationAmountField;
        
        private int multiUseClosePercentageField;
        
        private bool multiUseClosePercentageFieldSpecified;
        
        private string notesField;
        
        private string userReference1Field;
        
        private string userReference2Field;
        
        private string userReference3Field;
        
        private string userReference4Field;
        
        private string usernameField;
        
        private string fundingCurrencyCodeField;
        
        private System.Nullable<decimal> fxRateField;
        
        private bool fxRateFieldSpecified;
        
        private string quoteKeyField;
        
        private UserReference[] userReferencesField;
        
        private string rCNAliasField;
        
        private System.Nullable<int> accountIdField;
        
        private bool accountIdFieldSpecified;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivationDate {
            get {
                return this.activationDateField;
            }
            set {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardTypeName {
            get {
                return this.cardTypeNameField;
            }
            set {
                this.cardTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorReference {
            get {
                return this.integratorReferenceField;
            }
            set {
                this.integratorReferenceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInstantAuthRequired {
            get {
                return this.isInstantAuthRequiredField;
            }
            set {
                this.isInstantAuthRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMultiUse {
            get {
                return this.isMultiUseField;
            }
            set {
                this.isMultiUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsMultiUseSpecified {
            get {
                return this.isMultiUseFieldSpecified;
            }
            set {
                this.isMultiUseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IssuedToEcn {
            get {
                return this.issuedToEcnField;
            }
            set {
                this.issuedToEcnField = value;
            }
        }
        
        /// <remarks/>
        public long MaximumAuthorisationAmount {
            get {
                return this.maximumAuthorisationAmountField;
            }
            set {
                this.maximumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryCode {
            get {
                return this.merchantCategoryCodeField;
            }
            set {
                this.merchantCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryName {
            get {
                return this.merchantCategoryNameField;
            }
            set {
                this.merchantCategoryNameField = value;
            }
        }
        
        /// <remarks/>
        public long MinimumAuthorisationAmount {
            get {
                return this.minimumAuthorisationAmountField;
            }
            set {
                this.minimumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        public int MultiUseClosePercentage {
            get {
                return this.multiUseClosePercentageField;
            }
            set {
                this.multiUseClosePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultiUseClosePercentageSpecified {
            get {
                return this.multiUseClosePercentageFieldSpecified;
            }
            set {
                this.multiUseClosePercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference1 {
            get {
                return this.userReference1Field;
            }
            set {
                this.userReference1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference2 {
            get {
                return this.userReference2Field;
            }
            set {
                this.userReference2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference3 {
            get {
                return this.userReference3Field;
            }
            set {
                this.userReference3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference4 {
            get {
                return this.userReference4Field;
            }
            set {
                this.userReference4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FundingCurrencyCode {
            get {
                return this.fundingCurrencyCodeField;
            }
            set {
                this.fundingCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FxRate {
            get {
                return this.fxRateField;
            }
            set {
                this.fxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FxRateSpecified {
            get {
                return this.fxRateFieldSpecified;
            }
            set {
                this.fxRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuoteKey {
            get {
                return this.quoteKeyField;
            }
            set {
                this.quoteKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.PublicServices.vNett.Contracts.Data" +
            "Contracts")]
        public UserReference[] UserReferences {
            get {
                return this.userReferencesField;
            }
            set {
                this.userReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RCNAlias {
            get {
                return this.rCNAliasField;
            }
            set {
                this.rCNAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.enett.com/services/vnett/2011/10")]
    public partial class UserReference {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.enett.com/services/vnett/2010/09")]
    public partial class FxHistory {
        
        private string dateTimeField;
        
        private string userField;
        
        private string sellCurrencyCodeField;
        
        private string buyCurrencyCodeField;
        
        private long sellAmountField;
        
        private long buyAmountField;
        
        private decimal rateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SellCurrencyCode {
            get {
                return this.sellCurrencyCodeField;
            }
            set {
                this.sellCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BuyCurrencyCode {
            get {
                return this.buyCurrencyCodeField;
            }
            set {
                this.buyCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public long SellAmount {
            get {
                return this.sellAmountField;
            }
            set {
                this.sellAmountField = value;
            }
        }
        
        /// <remarks/>
        public long BuyAmount {
            get {
                return this.buyAmountField;
            }
            set {
                this.buyAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.enett.com/services/vnett/2010/09")]
    public partial class VanHistory {
        
        private string dateTimeField;
        
        private string activityTypeField;
        
        private string userField;
        
        private string currencyField;
        
        private long amountField;
        
        private string detailsField;
        
        private string subActivityTypeField;
        
        private System.Nullable<bool> underReviewField;
        
        private bool underReviewFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivityType {
            get {
                return this.activityTypeField;
            }
            set {
                this.activityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubActivityType {
            get {
                return this.subActivityTypeField;
            }
            set {
                this.subActivityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UnderReview {
            get {
                return this.underReviewField;
            }
            set {
                this.underReviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnderReviewSpecified {
            get {
                return this.underReviewFieldSpecified;
            }
            set {
                this.underReviewFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVNettFxQuoteResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelVNettVANResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmendVNettVANResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueVNettVANResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVNettVANResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class BaseResponse {
        
        private bool isSuccessfulField;
        
        private bool isSuccessfulFieldSpecified;
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorDescriptionField;
        
        private string supportLogIdField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSuccessfulSpecified {
            get {
                return this.isSuccessfulFieldSpecified;
            }
            set {
                this.isSuccessfulFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SupportLogId {
            get {
                return this.supportLogIdField;
            }
            set {
                this.supportLogIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class GetVNettFxQuoteResponse : BaseResponse {
        
        private decimal rateField;
        
        private bool rateFieldSpecified;
        
        private int quoteTimeoutField;
        
        private bool quoteTimeoutFieldSpecified;
        
        private string quoteKeyField;
        
        /// <remarks/>
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified {
            get {
                return this.rateFieldSpecified;
            }
            set {
                this.rateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int QuoteTimeout {
            get {
                return this.quoteTimeoutField;
            }
            set {
                this.quoteTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuoteTimeoutSpecified {
            get {
                return this.quoteTimeoutFieldSpecified;
            }
            set {
                this.quoteTimeoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string QuoteKey {
            get {
                return this.quoteKeyField;
            }
            set {
                this.quoteKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class CancelVNettVANResponse : BaseResponse {
        
        private int vNettTransactionIDField;
        
        private bool vNettTransactionIDFieldSpecified;
        
        /// <remarks/>
        public int VNettTransactionID {
            get {
                return this.vNettTransactionIDField;
            }
            set {
                this.vNettTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VNettTransactionIDSpecified {
            get {
                return this.vNettTransactionIDFieldSpecified;
            }
            set {
                this.vNettTransactionIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2012/03")]
    public partial class AmendVNettVANResponse : BaseResponse {
        
        private string activationDateField;
        
        private string authorisationCodeField;
        
        private string expiryDateField;
        
        private string fullExpiryDateField;
        
        private int vNettTransactionIDField;
        
        private string cardSecurityCodeField;
        
        private System.Nullable<decimal> fxRateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivationDate {
            get {
                return this.activationDateField;
            }
            set {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorisationCode {
            get {
                return this.authorisationCodeField;
            }
            set {
                this.authorisationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullExpiryDate {
            get {
                return this.fullExpiryDateField;
            }
            set {
                this.fullExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public int VNettTransactionID {
            get {
                return this.vNettTransactionIDField;
            }
            set {
                this.vNettTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardSecurityCode {
            get {
                return this.cardSecurityCodeField;
            }
            set {
                this.cardSecurityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FxRate {
            get {
                return this.fxRateField;
            }
            set {
                this.fxRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2013/07")]
    public partial class IssueVNettVANResponse : BaseResponse {
        
        private string activationDateField;
        
        private string authorisationCodeField;
        
        private string cardHolderNameField;
        
        private string cardSecurityCodeField;
        
        private string expiryDateField;
        
        private string fullExpiryDateField;
        
        private string generationDateField;
        
        private int vNettTransactionIDField;
        
        private bool vNettTransactionIDFieldSpecified;
        
        private string virtualAccountNumberField;
        
        private long minimumAuthorisationAmountField;
        
        private long maximumAuthorisationAmountField;
        
        private long fundedAmountField;
        
        private bool fundedAmountFieldSpecified;
        
        private string currencyCodeField;
        
        private string fundingCurrencyCodeField;
        
        private System.Nullable<decimal> fxRateField;
        
        private bool fxRateFieldSpecified;
        
        private string rCNAliasField;
        
        private string rCNDescriptionField;
        
        private decimal safetyMarginField;
        
        private bool safetyMarginFieldSpecified;
        
        private System.Nullable<int> accountIdField;
        
        private bool accountIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivationDate {
            get {
                return this.activationDateField;
            }
            set {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthorisationCode {
            get {
                return this.authorisationCodeField;
            }
            set {
                this.authorisationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardSecurityCode {
            get {
                return this.cardSecurityCodeField;
            }
            set {
                this.cardSecurityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullExpiryDate {
            get {
                return this.fullExpiryDateField;
            }
            set {
                this.fullExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GenerationDate {
            get {
                return this.generationDateField;
            }
            set {
                this.generationDateField = value;
            }
        }
        
        /// <remarks/>
        public int VNettTransactionID {
            get {
                return this.vNettTransactionIDField;
            }
            set {
                this.vNettTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VNettTransactionIDSpecified {
            get {
                return this.vNettTransactionIDFieldSpecified;
            }
            set {
                this.vNettTransactionIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VirtualAccountNumber {
            get {
                return this.virtualAccountNumberField;
            }
            set {
                this.virtualAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public long MinimumAuthorisationAmount {
            get {
                return this.minimumAuthorisationAmountField;
            }
            set {
                this.minimumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        public long MaximumAuthorisationAmount {
            get {
                return this.maximumAuthorisationAmountField;
            }
            set {
                this.maximumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        public long FundedAmount {
            get {
                return this.fundedAmountField;
            }
            set {
                this.fundedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FundedAmountSpecified {
            get {
                return this.fundedAmountFieldSpecified;
            }
            set {
                this.fundedAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FundingCurrencyCode {
            get {
                return this.fundingCurrencyCodeField;
            }
            set {
                this.fundingCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> FxRate {
            get {
                return this.fxRateField;
            }
            set {
                this.fxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FxRateSpecified {
            get {
                return this.fxRateFieldSpecified;
            }
            set {
                this.fxRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RCNAlias {
            get {
                return this.rCNAliasField;
            }
            set {
                this.rCNAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RCNDescription {
            get {
                return this.rCNDescriptionField;
            }
            set {
                this.rCNDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal SafetyMargin {
            get {
                return this.safetyMarginField;
            }
            set {
                this.safetyMarginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SafetyMarginSpecified {
            get {
                return this.safetyMarginFieldSpecified;
            }
            set {
                this.safetyMarginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2011/10")]
    public partial class GetVNettVANResponse : BaseResponse {
        
        private string activationDateField;
        
        private string cardHolderNameField;
        
        private string cardSecurityCodeField;
        
        private string cardTypeField;
        
        private string countryField;
        
        private string currencyField;
        
        private string fullExpiryDateField;
        
        private string integratorReferenceField;
        
        private bool isMultiUseField;
        
        private int issuedToECNField;
        
        private long maximumAuthorisationAmountField;
        
        private string merchantCategoryCodeField;
        
        private string merchantCategoryNameField;
        
        private long minimumAuthorisationAmountField;
        
        private string notesField;
        
        private int requesterECNField;
        
        private long totalAuthorisedAmountField;
        
        private long totalRefundedAmountField;
        
        private long totalSettledAmountField;
        
        private string userReference1Field;
        
        private string userReference2Field;
        
        private string userReference3Field;
        
        private string userReference4Field;
        
        private int vNettTransactionIDField;
        
        private VanHistory[] vanHistoryCollectionField;
        
        private string virtualAccountNumberField;
        
        private decimal multiClosePercentageField;
        
        private bool isFundedField;
        
        private string fundedCurrencyCodeField;
        
        private decimal fxRateField;
        
        private long fundedAmountField;
        
        private FxHistory[] fxHistoryCollectionField;
        
        private decimal availableBalanceField;
        
        private UserReference[] userReferencesField;
        
        private decimal netSettledAmountField;
        
        private decimal outstandingAuthorisationsField;
        
        private string rcnAliasField;
        
        private string rCNDescriptionField;
        
        private decimal fxFeeField;
        
        private string cardExpiryDateField;
        
        private decimal safetyMarginField;
        
        private bool safetyMarginFieldSpecified;
        
        private string channelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivationDate {
            get {
                return this.activationDateField;
            }
            set {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardSecurityCode {
            get {
                return this.cardSecurityCodeField;
            }
            set {
                this.cardSecurityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullExpiryDate {
            get {
                return this.fullExpiryDateField;
            }
            set {
                this.fullExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorReference {
            get {
                return this.integratorReferenceField;
            }
            set {
                this.integratorReferenceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMultiUse {
            get {
                return this.isMultiUseField;
            }
            set {
                this.isMultiUseField = value;
            }
        }
        
        /// <remarks/>
        public int IssuedToECN {
            get {
                return this.issuedToECNField;
            }
            set {
                this.issuedToECNField = value;
            }
        }
        
        /// <remarks/>
        public long MaximumAuthorisationAmount {
            get {
                return this.maximumAuthorisationAmountField;
            }
            set {
                this.maximumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryCode {
            get {
                return this.merchantCategoryCodeField;
            }
            set {
                this.merchantCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryName {
            get {
                return this.merchantCategoryNameField;
            }
            set {
                this.merchantCategoryNameField = value;
            }
        }
        
        /// <remarks/>
        public long MinimumAuthorisationAmount {
            get {
                return this.minimumAuthorisationAmountField;
            }
            set {
                this.minimumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public int RequesterECN {
            get {
                return this.requesterECNField;
            }
            set {
                this.requesterECNField = value;
            }
        }
        
        /// <remarks/>
        public long TotalAuthorisedAmount {
            get {
                return this.totalAuthorisedAmountField;
            }
            set {
                this.totalAuthorisedAmountField = value;
            }
        }
        
        /// <remarks/>
        public long TotalRefundedAmount {
            get {
                return this.totalRefundedAmountField;
            }
            set {
                this.totalRefundedAmountField = value;
            }
        }
        
        /// <remarks/>
        public long TotalSettledAmount {
            get {
                return this.totalSettledAmountField;
            }
            set {
                this.totalSettledAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference1 {
            get {
                return this.userReference1Field;
            }
            set {
                this.userReference1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference2 {
            get {
                return this.userReference2Field;
            }
            set {
                this.userReference2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference3 {
            get {
                return this.userReference3Field;
            }
            set {
                this.userReference3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference4 {
            get {
                return this.userReference4Field;
            }
            set {
                this.userReference4Field = value;
            }
        }
        
        /// <remarks/>
        public int VNettTransactionID {
            get {
                return this.vNettTransactionIDField;
            }
            set {
                this.vNettTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.PublicServices.vNett.Contracts.Data" +
            "Contracts")]
        public VanHistory[] VanHistoryCollection {
            get {
                return this.vanHistoryCollectionField;
            }
            set {
                this.vanHistoryCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VirtualAccountNumber {
            get {
                return this.virtualAccountNumberField;
            }
            set {
                this.virtualAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal MultiClosePercentage {
            get {
                return this.multiClosePercentageField;
            }
            set {
                this.multiClosePercentageField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFunded {
            get {
                return this.isFundedField;
            }
            set {
                this.isFundedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FundedCurrencyCode {
            get {
                return this.fundedCurrencyCodeField;
            }
            set {
                this.fundedCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal FxRate {
            get {
                return this.fxRateField;
            }
            set {
                this.fxRateField = value;
            }
        }
        
        /// <remarks/>
        public long FundedAmount {
            get {
                return this.fundedAmountField;
            }
            set {
                this.fundedAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.PublicServices.vNett.Contracts.Data" +
            "Contracts")]
        public FxHistory[] FxHistoryCollection {
            get {
                return this.fxHistoryCollectionField;
            }
            set {
                this.fxHistoryCollectionField = value;
            }
        }
        
        /// <remarks/>
        public decimal AvailableBalance {
            get {
                return this.availableBalanceField;
            }
            set {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.PublicServices.vNett.Contracts.Data" +
            "Contracts")]
        public UserReference[] UserReferences {
            get {
                return this.userReferencesField;
            }
            set {
                this.userReferencesField = value;
            }
        }
        
        /// <remarks/>
        public decimal NetSettledAmount {
            get {
                return this.netSettledAmountField;
            }
            set {
                this.netSettledAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal OutstandingAuthorisations {
            get {
                return this.outstandingAuthorisationsField;
            }
            set {
                this.outstandingAuthorisationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RcnAlias {
            get {
                return this.rcnAliasField;
            }
            set {
                this.rcnAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RCNDescription {
            get {
                return this.rCNDescriptionField;
            }
            set {
                this.rCNDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal FxFee {
            get {
                return this.fxFeeField;
            }
            set {
                this.fxFeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CardExpiryDate {
            get {
                return this.cardExpiryDateField;
            }
            set {
                this.cardExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal SafetyMargin {
            get {
                return this.safetyMarginField;
            }
            set {
                this.safetyMarginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SafetyMarginSpecified {
            get {
                return this.safetyMarginFieldSpecified;
            }
            set {
                this.safetyMarginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVNettFxQuoteRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelVNettVANRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AmendVNettVANRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IssueVNettVANRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetVNettVANRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class BaseRequest {
        
        private string integratorCodeField;
        
        private string integratorAccessKeyField;
        
        private int requesterECNField;
        
        private string messageDigestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorCode {
            get {
                return this.integratorCodeField;
            }
            set {
                this.integratorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorAccessKey {
            get {
                return this.integratorAccessKeyField;
            }
            set {
                this.integratorAccessKeyField = value;
            }
        }
        
        /// <remarks/>
        public int RequesterECN {
            get {
                return this.requesterECNField;
            }
            set {
                this.requesterECNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageDigest {
            get {
                return this.messageDigestField;
            }
            set {
                this.messageDigestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class GetVNettFxQuoteRequest : BaseRequest {
        
        private int clientEcnField;
        
        private bool clientEcnFieldSpecified;
        
        private string buyCurrencyField;
        
        private string sellCurrencyField;
        
        /// <remarks/>
        public int ClientEcn {
            get {
                return this.clientEcnField;
            }
            set {
                this.clientEcnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClientEcnSpecified {
            get {
                return this.clientEcnFieldSpecified;
            }
            set {
                this.clientEcnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BuyCurrency {
            get {
                return this.buyCurrencyField;
            }
            set {
                this.buyCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SellCurrency {
            get {
                return this.sellCurrencyField;
            }
            set {
                this.sellCurrencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.services.vnettservice.messages.v1")]
    public partial class CancelVNettVANRequest : BaseRequest {
        
        private CancelReasonType cancelReasonField;
        
        private string integratorReferenceField;
        
        private int issuedToEcnField;
        
        private bool issuedToEcnFieldSpecified;
        
        private string usernameField;
        
        /// <remarks/>
        public CancelReasonType CancelReason {
            get {
                return this.cancelReasonField;
            }
            set {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorReference {
            get {
                return this.integratorReferenceField;
            }
            set {
                this.integratorReferenceField = value;
            }
        }
        
        /// <remarks/>
        public int IssuedToEcn {
            get {
                return this.issuedToEcnField;
            }
            set {
                this.issuedToEcnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssuedToEcnSpecified {
            get {
                return this.issuedToEcnFieldSpecified;
            }
            set {
                this.issuedToEcnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.enett.com/services/vnett/2010/09")]
    public enum CancelReasonType {
        
        /// <remarks/>
        BookingCancelled,
        
        /// <remarks/>
        BookingAmended,
        
        /// <remarks/>
        DuplicateRequest,
        
        /// <remarks/>
        ErrorInOriginalRequest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2012/03")]
    public partial class AmendVNettVANRequest : BaseRequest {
        
        private string activationDateField;
        
        private string expiryDateField;
        
        private string integratorReferenceField;
        
        private bool isInstantAuthRequiredField;
        
        private bool isMultiUseField;
        
        private bool isMultiUseFieldSpecified;
        
        private int issuedToEcnField;
        
        private long maximumAuthorisationAmountField;
        
        private string merchantCategoryCodeField;
        
        private string merchantCategoryNameField;
        
        private long minimumAuthorisationAmountField;
        
        private int multiUseClosePercentageField;
        
        private bool multiUseClosePercentageFieldSpecified;
        
        private string notesField;
        
        private string userReference1Field;
        
        private string userReference2Field;
        
        private string userReference3Field;
        
        private string userReference4Field;
        
        private string usernameField;
        
        private string fundingCurrencyCodeField;
        
        private UserReference[] userReferencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ActivationDate {
            get {
                return this.activationDateField;
            }
            set {
                this.activationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorReference {
            get {
                return this.integratorReferenceField;
            }
            set {
                this.integratorReferenceField = value;
            }
        }
        
        /// <remarks/>
        public bool IsInstantAuthRequired {
            get {
                return this.isInstantAuthRequiredField;
            }
            set {
                this.isInstantAuthRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsMultiUse {
            get {
                return this.isMultiUseField;
            }
            set {
                this.isMultiUseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsMultiUseSpecified {
            get {
                return this.isMultiUseFieldSpecified;
            }
            set {
                this.isMultiUseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IssuedToEcn {
            get {
                return this.issuedToEcnField;
            }
            set {
                this.issuedToEcnField = value;
            }
        }
        
        /// <remarks/>
        public long MaximumAuthorisationAmount {
            get {
                return this.maximumAuthorisationAmountField;
            }
            set {
                this.maximumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryCode {
            get {
                return this.merchantCategoryCodeField;
            }
            set {
                this.merchantCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MerchantCategoryName {
            get {
                return this.merchantCategoryNameField;
            }
            set {
                this.merchantCategoryNameField = value;
            }
        }
        
        /// <remarks/>
        public long MinimumAuthorisationAmount {
            get {
                return this.minimumAuthorisationAmountField;
            }
            set {
                this.minimumAuthorisationAmountField = value;
            }
        }
        
        /// <remarks/>
        public int MultiUseClosePercentage {
            get {
                return this.multiUseClosePercentageField;
            }
            set {
                this.multiUseClosePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultiUseClosePercentageSpecified {
            get {
                return this.multiUseClosePercentageFieldSpecified;
            }
            set {
                this.multiUseClosePercentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference1 {
            get {
                return this.userReference1Field;
            }
            set {
                this.userReference1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference2 {
            get {
                return this.userReference2Field;
            }
            set {
                this.userReference2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference3 {
            get {
                return this.userReference3Field;
            }
            set {
                this.userReference3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserReference4 {
            get {
                return this.userReference4Field;
            }
            set {
                this.userReference4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FundingCurrencyCode {
            get {
                return this.fundingCurrencyCodeField;
            }
            set {
                this.fundingCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/eNett.PublicServices.vNett.Contracts.Data" +
            "Contracts")]
        public UserReference[] UserReferences {
            get {
                return this.userReferencesField;
            }
            set {
                this.userReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://enett.com/services/messages/2011/10")]
    public partial class GetVNettVANRequest : BaseRequest {
        
        private string integratorReferenceField;
        
        private string virtualAccountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IntegratorReference {
            get {
                return this.integratorReferenceField;
            }
            set {
                this.integratorReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VirtualAccountNumber {
            get {
                return this.virtualAccountNumberField;
            }
            set {
                this.virtualAccountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IssueVANCompletedEventHandler(object sender, IssueVANCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IssueVANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IssueVANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IssueVNettVANResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IssueVNettVANResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AmendVANCompletedEventHandler(object sender, AmendVANCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AmendVANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AmendVANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AmendVNettVANResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AmendVNettVANResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CancelVANCompletedEventHandler(object sender, CancelVANCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelVANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelVANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelVNettVANResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelVNettVANResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetVANDetailsCompletedEventHandler(object sender, GetVANDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVANDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVANDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetVNettVANResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetVNettVANResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetFxQuoteCompletedEventHandler(object sender, GetFxQuoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFxQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFxQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetVNettFxQuoteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetVNettFxQuoteResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591